version: '3.7'
services:
  postgres-db:
    container_name: posgres-db
    image: postgres:14-bookworm
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "54321:5432"
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:25.0
    ports:
      - "9080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin 
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin